steps:
  - name: openjdk:17
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew check

  - name: openjdk:17
    id: build-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        ./gradlew bootBuildImage --imageName=us-docker.pkg.dev/$PROJECT_ID/docker-repo/hello-cloud-run-sample:$SHORT_SHA

  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy
    args: [ 'run', 'deploy', "--image=us-docker.pkg.dev/$PROJECT_ID/docker-repo/hello-cloud-run-sample:$SHORT_SHA", '--platform=managed', '--project=$PROJECT_ID', '--region=us-central1', '--allow-unauthenticated', '--memory=256Mi', '--set-env-vars=SPRING_PROFILES_ACTIVE=gcp', 'hello-cloud-run-sample' ]
images:
  - us-docker.pkg.dev/$PROJECT_ID/docker-repo/hello-cloud-run-sample:$SHORT_SHA